### ISSUE TITLE
Question related to react/js/execution/es6

### ISSUE THREAD

**Issue by 12sam12** [trekhleb/javascript-algorithms#834] opened 2022-01-16 02:59 UTC
Lets consider the following screenshot:
![image](https://user-images.githubusercontent.com/13358855/149645488-c515f9e1-140c-4843-aea5-d657797b33ab.png)
![image](https://user-images.githubusercontent.com/13358855/149645544-bb32c50e-f7bd-4670-8a32-c01ee4bf8703.png)

Even after the control reaches the let assignment statement, the previous imports are undefined. Could anyone explain why is that so?
Also the following shows that the bundled internal variables are defined though:
![image](https://user-images.githubusercontent.com/13358855/149645560-e0595dfe-bdfc-494d-8a07-f373a2a7095a.png)
![image](https://user-images.githubusercontent.com/13358855/149645562-10f8ed38-7309-48a9-ac18-31c8430e3ff1.png)
Why does this behavior exist in javascript? Is this expected or something different.
Its in mozilla firefox browser (95.0.1)

 As far as I know as javascript is a synchronous language except the specific functionalities like promises, async/await, I guess everything else must be synchronous by its design, which is why this unpredictability in its behavior is confusing.

**Comment by trekhleb** [comment] 2022-01-23 21:36
The issue is out of scope for this repository

**Closed by trekhleb** 2022-01-23 21:36 UTC
